import { ReactNode } from "react";
import { Merriweather_Sans } from "next/font/google";
import clsx from "clsx";
import "./globals.css";

const merriweather = Merriweather_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang="en">
    <body
      className={clsx(
        "mx-auto my-32 max-w-2xl bg-orange-50/25",
        merriweather.className
      )}
    >
      <main>{children}</main>
    </body>
  </html>
);

export default RootLayout;
